<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="inlen8520069246" failures="1" tests="3" name="Error Validation Test" time="76.33" errors="0" timestamp="2023-04-18T07:49:58 IST">
  <testcase classname="automationlearning.testcomponents.ErrorValidationTest" name="loginErrorValidation" time="0.24">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="automationlearning.testcomponents.ErrorValidationTest" name="loginErrorValidation" time="0.177">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at automationlearning.testcomponents.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="automationlearning.testcomponents.ErrorValidationTest" name="productValidation" time="2.475"/>
</testsuite> <!-- Error Validation Test -->
